# Generated by Django 4.2.7 on 2026-01-22 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_avatar_alter_consultation_expert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paysan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('type_culture', models.CharField(max_length=150)),
                ('superficie', models.FloatField(help_text='Superficie en hectares')),
                ('experience', models.IntegerField(help_text="Années d'expérience agricole")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paysan_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
