# Generated by Django 4.2.7 on 2026-05-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='type_animal',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
