# Generated by Django 4.2.7 on 2026-04-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_paysan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('paysan', 'Paysan'), ('expert', 'Expert'), ('admin', 'Admin')], default='paysan', max_length=20),
        ),
    ]
