# Generated by Django 4.2.7 on 2026-05-01 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elevage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_animal', models.CharField(choices=[('poulet', 'Poulet'), ('vache', 'Vache'), ('chevre', 'Chèvre'), ('mouton', 'Mouton'), ('porc', 'Porc'), ('poisson', 'Poisson'), ('autre', 'Autre')], max_length=50)),
                ('nom', models.CharField(help_text="Nom de l'élevage ou du projet", max_length=150)),
                ('nombre', models.PositiveIntegerField()),
                ('systeme', models.CharField(choices=[('intensif', 'Intensif'), ('extensif', 'Extensif'), ('semi-intensif', 'Semi-intensif')], default='extensif', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('localisation', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elevages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuiviSante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maladie', models.CharField(max_length=150)),
                ('traitement', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('elevage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sante', to='core.elevage')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_production', models.CharField(choices=[('lait', 'Lait'), ('oeufs', 'Œufs'), ('viande', 'Viande'), ('poisson', 'Poisson')], max_length=50)),
                ('quantite', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('elevage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='core.elevage')),
            ],
        ),
    ]
