# Generated by Django 4.2.7 on 2026-05-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_elevage_suivisante_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('paysan', 'Paysan'), ('expert', 'Expert'), ('admin', 'Admin'), ('eleveur', 'Eleveur')], default='paysan', max_length=20),
        ),
    ]
